DROP DATABASE IF EXISTS pdvPlanBTech;
CREATE DATABASE pdvPlanBTech;
USE pdvPlanBTech;

CREATE TABLE IF NOT EXISTS cargos(
	id_Cargo INTEGER PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS funcionario(
	id_Funcionario INTEGER PRIMARY KEY AUTO_INCREMENT,
    id_Cargo INTEGER NOT NULL,
    Nome VARCHAR(50) NOT NULL,
    Sobrenome VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuario(
	id_Usuario	INTEGER PRIMARY KEY AUTO_INCREMENT,
	id_Funcionario	INTEGER NOT NULL,
	Usuario 			VARCHAR(50),
	Senha			VARCHAR(50),
	Permissao INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS receita(
	id_Receita 		INTEGER NOT NULL,
	id_Ingrediente  INTEGER NOT NULL,
	Nome_receita VARCHAR(50),
    Valor DECIMAL(8 ,2)
);

CREATE TABLE IF NOT EXISTS ingredientes(
	id_Ingrediente INTEGER PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(30) NOT NULL UNIQUE,
    borda BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS carrinho(
	id_Carrinho INTEGER,
	id_Receita INTEGER NOT NULL,
    Valor DECIMAL(8, 2),
    Borda INTEGER NOT NULL,
    Qtd INTEGER
);

CREATE TABLE IF NOT EXISTS pedido(
	id_Pedido INTEGER PRIMARY KEY AUTO_INCREMENT,
    id_Funcionario INTEGER NOT NULL,
    id_Carrinho INTEGER NOT NULL,
    Cliente VARCHAR(50),
    Observacao VARCHAR (100),
    Valor_Total DECIMAL(8,2),
    Status_pedido INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS estoque(
	id_Produto INTEGER PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(50) NOT NULL,
    Quantidade INTEGER NOT NULL,
    Recebimento DATETIME DEFAULT CURRENT_TIMESTAMP(),
    Vencimento DATETIME,
    tipo_Ingrediente INTEGER, #mussarela, refri
    Valor_de_Compra DECIMAL(10,2)
);