#INSERTS
USE pdvPlanBTech;

INSERT INTO cargos (nome) VALUES 
("Gerente"),
("Atendente");

INSERT INTO ingredientes (nome, borda) VALUES
('mussarela', TRUE),
('tomate', FALSE),
('alho frito', FALSE),
('cebola', FALSE),
('frango', FALSE),
('catupiry', TRUE),
('milho', FALSE),
('presunto', FALSE),
('ovo', FALSE),
('bacon', FALSE),
('brócolis', FALSE),
('champignon', FALSE),
('palmito', FALSE),
('calabresa', FALSE),
('carne moida', FALSE),
('pimentão', FALSE),
('parmesão', FALSE),
('gorgonzola', FALSE),
('banana', FALSE),
('doce de leite', TRUE),
('canela', FALSE),
('nutela', TRUE),
('morango', FALSE),
('granulado', FALSE),
('cheddar', TRUE),
('cream cheese', TRUE),
('molho de tomate', FALSE),
('azeitona', FALSE),
('kinder bueno', FALSE),
('creme branco', FALSE);

INSERT INTO receita VALUES
(1, 1, 'mussarela'),
(1, 2, 'mussarela'),
(1, 27, 'mussarela'),
(1, 28, 'mussarela'),
(2, 1, 'alho frito'),
(2, 3, 'alho frito'),
(2, 24, 'alho frito'),
(2, 27, 'alho frito'),
(2, 28, 'alho frito'),
(3, 5, 'frango c/ catupiry'),
(3, 6, 'frango c/ catupiry'),
(3, 7, 'frango c/ catupiry'),
(3, 4, 'frango c/ catupiry'),
(3, 27, 'frango c/ catupiry'),
(3, 28, 'frango c/ catupiry'),
(4, 1, 'portuguesa'),
(4, 8, 'portuguesa'),
(4, 9, 'portuguesa'),
(4, 4, 'portuguesa'),
(4, 27, 'portuguesa'),
(4, 28, 'portuguesa'),
(5, 10, 'brócolis'),
(5, 11, 'brócolis'),
(5, 1, 'brócolis'),
(5, 27, 'brócolis'),
(5, 28, 'brócolis'),
(6, 1, 'vegetariana'),
(6, 11, 'vegetariana'),
(6, 12, 'vegetariana'),
(6, 13, 'vegetariana'),
(6, 27, 'vegetariana'),
(6, 28, 'vegetariana'),
(7, 1, 'calabresa'),
(7, 4, 'calabresa'),
(7, 14, 'calabresa'),
(7, 27, 'calabresa'),
(7, 28, 'calabresa'),
(8, 1, 'bacon'),
(8, 4, 'bacon'),
(8, 10, 'bacon'),
(8, 27, 'bacon'),
(8, 28, 'bacon'),
(9, 1, 'moda da casa'),
(9, 5, 'moda da casa'),
(9, 10, 'moda da casa'),
(9, 14, 'moda da casa'),
(9, 27, 'moda da casa'),
(9, 28, 'moda da casa'),
(10, 1, 'bolonhesa'),
(10, 15, 'bolonhesa'),
(10, 16, 'bolonhesa'),
(10, 4, 'bolonhesa'),
(10, 27, 'bolonhesa'),
(10, 28, 'bolonhesa'),
(11, 1, '4 queijos'),
(11, 6, '4 queijos'),
(11, 17, '4 queijos'),
(11, 18, '4 queijos'),
(11, 27, '4 queijos'),
(11, 28, '4 queijos'),
(12, 19, 'banana'),
(12, 20, 'banana'),
(12, 21, 'banana'),
(13, 22, 'nutella com morango'),
(13, 23, 'nutella com morango'),
(13, 24, 'nutella com morango'),
(14, 29, 'kinder Bueno'),
(14, 30, 'kinder Bueno');

CALL cadFunc('douglas', 'machado', 'gerente');
CALL cadFunc('test', 'test', 'atendente');
CALL cadFunc('Yago', 'Henrique', 'Atendente');

CALL cadUsuario("douglas", "machado","doug","1234", 1);

CALL cadUsuario("Yago", "Henrique", "hfa", "root", 0);

CALL insertEstoque(3, 'Mussarela Jussara 5KG', 'mussarela', 4.50);
CALL insertEstoque(4, 'Na brasa Calabresa 10 KG', 'calabresa', 7);

